services:
  sender:
    container_name: sender
    image: nginx:1.29.5
    ports: ["443:443", "80:80"]
    volumes: ["./sender:/sender:ro"]
    command: ["nginx", "-c", "/sender/nginx.conf"]

  backend:
    container_name: server
    image: node:latest
    build: .
    volumes: ["./:/app",]
    ports: ["4000:4000"]
    command: ["npx", "node", "/backend/dist/server.js"]

