daemon off;
user root;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;

  server {
    listen 80;
    root /home/user/projects/contacts-manager/sender/public;
    location / {
      try_files $uri index.html;
    }
  }
}