on: [push, pull_request]

jobs:
  frontend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm --prefix=frontend install

      - name: Tests
        run: pnpm --prefix=frontend vitest -- --run

  backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm --prefix=backend install

      - name: Compile backend
        run: pnpm --prefix=backend exec tsc

      - name: Start backend
        run: node ./backend/dist/server.js &

      - name: Waiting for start
        run: pnpm exec wait-on http://localhost:8000 --timeout 1000

      - name: Tests
        run: pnpm --prefix=backend vitest -- --run