on: [push, pull_request]

jobs:
  always-pass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Simple success
        run: echo "This workflow always passes ✅"